secrets:
  serverEnv:
    file: ./.env

services:
  postgres:
    build:
      context: .
      dockerfile: ./pg/Dockerfile
      network: host
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./pg/postgresql.conf:/etc/postgresql.conf
      - ./pg/logs:/var/log/postgresql
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_USER=pglin
      - POSTGRES_DB=linker_db
    container_name: linker_postgresdb
    restart: always
    command: [ "postgres", "-c", "config_file=/etc/postgresql.conf" ]

  minio:
    image: minio/minio:latest
    container_name: linker_minio
    restart: always
    network_mode: host
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --address 127.0.0.1:6603 --console-address 127.0.0.1:6604
    volumes:
      - ./minio-data:/data

  panel:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    network_mode: host
    environment:
      - RUST_LOG=info
    volumes:
      - ./.env:/.env
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL=info
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-6606}:7700
    networks:
      - panelnet
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped

  
networks:
  panelnet:
    driver: bridge